PR for issue #206 [翻译] Zero-Trust Security with Service Mesh
cloudnativeto/cloudnative.to pull request #211
Opened 2020-10-18 06:01 UTC by myf5

> 请保留以下声明。

我已阅读[投稿指南](https://cloudnative.to/contribute/)和[风格指南](https://cloudnative.to/style-guides/)，并授权[云原生社区](https://cloudnative.to)发布我原创或翻译的文章，我将保留对本文署名的权利。

2020-10-18 06:18 UTC, myf5 commented
preview passed~thanks.

2020-10-21 00:15 UTC, myf5 commented
自查 修正了头像放置位置

2020-10-21 06:42 UTC, hyfj44255 commented
Hi，review了一下你的翻译，提了pr，要是没问题麻烦合并下，谢谢https://github.com/myf5/cloudnative.to/pull/1

2020-10-21 06:42 UTC, hyfj44255 reviewed
Hi，review了一下翻译，提了pr，要是没问题麻烦合并下，谢谢https://github.com/myf5/cloudnative.to/pull/1

2020-10-21 06:55 UTC, myf5 commented
merged review result

2020-10-21 07:23 UTC, rootsongjc commented on content/zh/blog/zero-trust-service-mesh/index.md
> +description: "本文翻译自 Rose Sawvel 的文章 Zero-Trust Security with Service Mesh"
```suggestion
description: "本文翻译自 Rose Sawvel 的文章 Zero-Trust Security with Service Mesh。"
```

2020-10-21 07:23 UTC, rootsongjc commented on content/zh/blog/zero-trust-service-mesh/index.md
> +description: "本文翻译自 Rose Sawvel 的文章 Zero-Trust Security with Service Mesh"
句子最后要加句号。

2020-10-21 07:23 UTC, rootsongjc commented on content/zh/blog/zero-trust-service-mesh/index.md
> +categories: ["service-mesh"]
```suggestion
categories: ["Service Mesh"]
```

2020-10-21 07:23 UTC, rootsongjc commented on content/zh/blog/zero-trust-service-mesh/index.md
> +categories: ["service-mesh"]
直接这么写就好了。

2020-10-21 07:24 UTC, rootsongjc commented on content/zh/blog/zero-trust-service-mesh/index.md
> +为了在 2020 年迎接这些需求和挑战，有 [ 53% 的网络安全决策者](https://www.pulsesecure.net/resource/2020zero-trust-report/) 计划迁移到零信任访问功能。谁能说他们是太小心了呢？
```suggestion
为了在 2020 年迎接这些需求和挑战，有 [53% 的网络安全决策者](https://www.pulsesecure.net/resource/2020zero-trust-report/) 计划迁移到零信任访问功能。谁能说他们是太小心了呢？
```

2020-10-21 07:25 UTC, rootsongjc requested changes
需要修改。

2020-10-21 07:35 UTC, rootsongjc approved these changes
/LGTM

2020-10-21 07:36 UTC, merged