PR for issue #205 [翻译] Introducing NGINX Service Mesh
cloudnativeto/cloudnative.to pull request #214
Opened 2020-10-19 01:50 UTC by hmtai

> 请保留以下声明。

我已阅读[投稿指南](https://cloudnative.to/contribute/)和[风格指南](https://cloudnative.to/style-guides/)，并授权[云原生社区](https://cloudnative.to)发布我原创或翻译的文章，我将保留对本文署名的权利。

2020-10-20 12:54 UTC, myf5 commented on content/zh/blog/nginx-service-mesh/index.md
> +categories: ["Service Mesh"]
categories: ["service-mesh"]

2020-10-20 12:57 UTC, myf5 commented on content/zh/blog/nginx-service-mesh/index.md
> +author: "Lis"
author: "Amir Rawdat"
Translator: "Lis"

2020-10-21 01:03 UTC, hyfj44255 commented
@Lis Hi，review了格式和内容，请参考修改谢谢。https://github.com/hmtai/cloudnative.to/pull/1

2020-10-21 03:28 UTC, hyfj44255 approved these changes
/LGTM

2020-10-21 07:06 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +profile: "由 Nginx 公司开发，一个完全集成的轻量级服务网格，它利用 NGINX Plus 支持的数据平面来管理 Kubernetes 环境中的容器流量。"
profile 里是介绍作者的，目前看来是介绍 NGINX 服务网格。

2020-10-21 07:06 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +控制平面是为 NGINX Plus 数据平面设计和优化的，并定义了分配给 NGINX Plus 边车容器的流量管理规则。
不要翻译 sidecar，把全文中的”边车”都换成 sidecar。

2020-10-21 07:06 UTC, rootsongjc requested changes
需要修改。

2020-10-21 07:08 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +translator: "[Lis](https://github.com/hmtai)"
请写上大名，本站所有帖子实名。

2020-10-21 07:34 UTC, hmtai commented on content/zh/blog/nginx-service-mesh/index.md
> +translator: "[Lis](https://github.com/hmtai)"
Done.

2020-10-21 07:37 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +NGINX Plus 作为数据平面跨越了sidecar代理（东西方流量）和入口控制器（南北流量），同时拦截和管理服务容器之间的流量。功能包括：
可以使用 pangu 格式化下本文，sidecar 和中文之间没有加空格。

2020-10-21 07:37 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +```
```suggestion
```bash
```

2020-10-21 07:37 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +```
```suggestion
```bash
```

2020-10-21 07:38 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +```
```suggestion
```bash
```

2020-10-21 07:38 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +![image](https://user-images.githubusercontent.com/37067719/96204792-c5539680-0f97-11eb-843e-2298c9cd111b.png)
图片需要有标题。

2020-10-21 07:38 UTC, rootsongjc requested changes
需要修改。

2020-10-21 08:00 UTC, hmtai commented
@rootsongjc Please review.

2020-10-21 10:07 UTC, rootsongjc commented on content/zh/blog/nginx-service-mesh/index.md
> +cription: "本文翻译自 Nginx 官方博客初识 NGINX 服务网格。"
头没有了？？

2020-10-21 11:35 UTC, hyfj44255 commented on content/zh/blog/nginx-service-mesh/index.md
> +profile: "台慧敏，程序员， 从事私有云开发，对容器，服务网格感兴趣，希望与大家分享更多新技术，共同学习进步。"
“从事”，之前没有空格

2020-10-23 00:22 UTC, myf5 commented
看已经都commit了

2020-10-23 01:29 UTC, hmtai commented
@rootsongjc Please review.

2020-10-23 03:01 UTC, rootsongjc approved these changes
/LGTM

2020-10-23 03:01 UTC, merged