Translate Running database migrations when deploying to Kubernetes
cloudnativeto/cloudnative.to pull request #410
Opened 2021-07-11 07:16 UTC by nicksu-kdkd

#409

> 请保留以下声明。

我已阅读[投稿指南](https://cloudnative.to/contribute/)和[风格指南](https://cloudnative.to/style-guides/)，并授权[云原生社区](https://cloudnative.to)发布我原创或翻译的文章，我将保留对本文署名的权利。

2021-07-12 00:30 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +originallink: "https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/"
这个配置没有用，直接作为作者的链接即可。

2021-07-12 00:30 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +author: "Andrew Lock"
```suggestion
author: "[Andrew Lock](https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/)"
```

2021-07-12 00:30 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +在这篇文章中，我会介绍如何解决部署应用到多副本应用的生产环境时会碰到的一个经典问题： 数据库 schema 更新。
这句话不通顺。

2021-07-12 00:31 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +接下来将会讨论几种可能的解决方案，从简单到复杂。最后会总结一下我在生产环境时如何解决这个问题的：使用 Kubernetes Jobs 和 init containers. 了解了这些解决方案（最重要的是谨慎的设计数据库 schema 更新）你可以比较从容的应对应用升级时的数据库数据更新的问题。
英文不需要复数，请使用中文句话。

2021-07-12 00:31 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +## Making database migrations safe
标题没翻译。

2021-07-12 00:32 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +![blog-engine](./pics/blog-engine.svg)
不要使用 svg 图片，请截图成 png 或者 jpg。

2021-07-12 00:32 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +```
代码请指定编程语言。

2021-07-12 01:46 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +```
已指定

2021-07-12 01:46 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +![blog-engine](./pics/blog-engine.svg)
已统一成 png

2021-07-12 01:46 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +## Making database migrations safe
抱歉，遗漏了，已经翻译

2021-07-12 01:46 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +接下来将会讨论几种可能的解决方案，从简单到复杂。最后会总结一下我在生产环境时如何解决这个问题的：使用 Kubernetes Jobs 和 init containers. 了解了这些解决方案（最重要的是谨慎的设计数据库 schema 更新）你可以比较从容的应对应用升级时的数据库数据更新的问题。
已修改

2021-07-12 01:47 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +在这篇文章中，我会介绍如何解决部署应用到多副本应用的生产环境时会碰到的一个经典问题： 数据库 schema 更新。
已改正

2021-07-12 01:47 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +author: "Andrew Lock"
已修改

2021-07-12 01:47 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +originallink: "https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/"
已删除

2021-07-12 06:38 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +接下来将会讨论几种可能的解决方案，从简单到复杂。最后会总结一下我在生产环境时如何解决这个问题的：使用 Kubernetes Job 和 init container. 了解了这些解决方案（最重要的是谨慎的设计数据库 schema 更新）你可以比较从容的应对应用升级时的数据库数据更新的问题。
```suggestion
接下来将会讨论几种可能的解决方案，从简单到复杂。最后会总结一下我在生产环境时如何解决这个问题的：使用 Kubernetes Job 和 init container。了解了这些解决方案（最重要的是谨慎的设计数据库 schema 更新）你可以比较从容的应对应用升级时的数据库更新的问题。
```

2021-07-12 06:39 UTC, rootsongjc commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +这些方式都类似的会记录那些已经应用在数据库中的更新，哪些还没有更新，并执行那些待更新的部分将变更部署到数据库里面，但是这些工具无法控制的一点就是什么时候去部署那些变更。
那些还是哪些？

2021-07-12 14:02 UTC, hyfj44255 requested changes
文中 database migrations 都翻译成了“数据库更新”，建议翻译为“数据库迁移”。

2021-07-13 10:17 UTC, hyfj44255 commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +实际操作中，数据库新的 schema 应该是可以适配于旧版本的应用，也就是说你不能给已存在的表格插入 NOT NULL 的列，因为应用并不知道哪一列会无法插入。所以要不就把新加的列设置为必须项，这样在接下来的部署中就会强制插入数据，或者配置一个默认值，来确保这一列是非空的。
建议“表格”改为“表”

2021-07-13 10:17 UTC, hyfj44255 commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +第二点其实是安全相关的，数据库更新是一项很危险的操作，因为它有机会导致数据丢失或者毁坏。比较安全的做法是日常应用运行时跟数据库更新时使用不同的数据库账户， 这样能减少应用运行时意外（或者恶意）的数据丢失的发生机率。 如果应用没有权限执行 `DROP` 表格的动作，那就几乎没有这种意外发生的机会了。
建议“表格”改为“表”

2021-07-13 10:17 UTC, hyfj44255 commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +这正正是我们想要用来做数据库数据更新的办法，创建一个 job 来执行数据库的 CLI 工具，出现网络问题时可以有选择的重试。因为它是一个 Kubernetes 原生概念，因此我們可以利用 Helm 的功能來模板化管理，将它包含在我们应用的 helm chart 里面。 从下面的图片可以看到，我给 test-app 添加了一個 CLI 项目，主要是一个 job.yaml。
开头多了一个“正”字

2021-07-13 10:17 UTC, hyfj44255 commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +这正正是我们想要用来做数据库数据更新的办法，创建一个 job 来执行数据库的 CLI 工具，出现网络问题时可以有选择的重试。因为它是一个 Kubernetes 原生概念，因此我們可以利用 Helm 的功能來模板化管理，将它包含在我们应用的 helm chart 里面。 从下面的图片可以看到，我给 test-app 添加了一個 CLI 项目，主要是一个 job.yaml。
这句话里面怎么有不少繁体字

2021-07-13 10:17 UTC, hyfj44255 commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +如果你还记得这一系列文章里的第一篇，我讲过 Pod 是 Kubernetes 里包含一个或者多个容器的最小的调度单位。大部分情况下，Pod 会有一个主容器提供应用的主要功能，可能还会有一个或者多个“边车”容器提供一些附加的功能，比如说 metrics 或者 service-mesh。
建议“边车”，还原为 side car

2021-07-15 09:24 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +这些方式都类似的会记录那些已经应用在数据库中的更新，哪些还没有更新，并执行那些待更新的部分将变更部署到数据库里面，但是这些工具无法控制的一点就是什么时候去部署那些变更。
部署那些变更 ==> 部署变更

2021-07-15 09:27 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +## 简单的更新策略
谢谢，这个我还是保留“简单的更新策略”

2021-07-15 09:30 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +- 已创建 categories 表格和 category_id 列
是的，这样更贴近数据库用语

2021-07-15 09:31 UTC, nicksu-kdkd commented on content/zh/blog/running-database-migration-when-deploying-to-kubernetes/index.md
> +实际操作中，数据库新的 schema 应该是可以适配于旧版本的应用，也就是说你不能给已存在的表格插入 NOT NULL 的列，因为应用并不知道哪一列会无法插入。所以要不就把新加的列设置为必须项，这样在接下来的部署中就会强制插入数据，或者配置一个默认值，来确保这一列是非空的。
谢谢，已经将所有 “表格” 改成 “表”

2021-07-15 12:16 UTC, rootsongjc approved these changes
LGTM

2021-07-15 12:18 UTC, rootsongjc commented
> 文中 database migrations 都翻译成了“数据库更新”，建议翻译为“数据库迁移”。

这个可以先合并后，我统一替换下。

2021-07-15 12:19 UTC, merged